/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.*;


/**
 *
 * @author Nabeel Hussain Syed
 */
public class StudentMenu extends javax.swing.JFrame{
private static String userName;

int check;


/**
     * Creates new form StudentMenu
     */
    public StudentMenu(String username) {
        userName = username.toUpperCase();
        initComponents();
        WelcomeMessage.setText("WELCOME "+userName+"!");
        QuizzesPanel.setVisible(false);
        SelectButton1.setVisible(false);
        SelectButton2.setVisible(false);
        SelectButton3.setVisible(false);
        SelectButton4.setVisible(false);
        SelectButton5.setVisible(false);
        SelectButton6.setVisible(false);
        SelectButton7.setVisible(false);
        
        Quiz showQuizzes = DeserializeData();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentMenuPanel = new javax.swing.JPanel();
        WelcomeMessage = new java.awt.Label();
        QuizzesPanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SelectButton1 = new java.awt.Button();
        Title1 = new java.awt.Label();
        Description1 = new java.awt.Label();
        Title2 = new java.awt.Label();
        Description2 = new java.awt.Label();
        Title3 = new java.awt.Label();
        Description3 = new java.awt.Label();
        SelectButton3 = new java.awt.Button();
        Title4 = new java.awt.Label();
        Description4 = new java.awt.Label();
        SelectButton4 = new java.awt.Button();
        Title5 = new java.awt.Label();
        Description5 = new java.awt.Label();
        SelectButton5 = new java.awt.Button();
        Title6 = new java.awt.Label();
        Description6 = new java.awt.Label();
        SelectButton6 = new java.awt.Button();
        Title7 = new java.awt.Label();
        Description7 = new java.awt.Label();
        SelectButton7 = new java.awt.Button();
        SelectButton2 = new java.awt.Button();
        ShowQuizzes = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        StudentMenuPanel.setAutoscrolls(true);

        WelcomeMessage.setAlignment(java.awt.Label.CENTER);
        WelcomeMessage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        WelcomeMessage.setForeground(new java.awt.Color(0, 0, 51));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label1.setText("Title");

        label2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Description");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Select to Attempt");

        SelectButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton1.setLabel("Select");
        SelectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton1ActionPerformed(evt);
            }
        });

        Title1.setAlignment(java.awt.Label.CENTER);
        Title1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description1.setAlignment(java.awt.Label.CENTER);
        Description1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Title2.setAlignment(java.awt.Label.CENTER);
        Title2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description2.setAlignment(java.awt.Label.CENTER);
        Description2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Title3.setAlignment(java.awt.Label.CENTER);
        Title3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description3.setAlignment(java.awt.Label.CENTER);
        Description3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        SelectButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton3.setLabel("Select");
        SelectButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton3ActionPerformed(evt);
            }
        });

        Title4.setAlignment(java.awt.Label.CENTER);
        Title4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description4.setAlignment(java.awt.Label.CENTER);
        Description4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        SelectButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton4.setLabel("Select");
        SelectButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton4ActionPerformed(evt);
            }
        });

        Title5.setAlignment(java.awt.Label.CENTER);
        Title5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description5.setAlignment(java.awt.Label.CENTER);
        Description5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        SelectButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton5.setLabel("Select");
        SelectButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton5ActionPerformed(evt);
            }
        });

        Title6.setAlignment(java.awt.Label.CENTER);
        Title6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description6.setAlignment(java.awt.Label.CENTER);
        Description6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        SelectButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton6.setLabel("Select");
        SelectButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton6ActionPerformed(evt);
            }
        });

        Title7.setAlignment(java.awt.Label.CENTER);
        Title7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Description7.setAlignment(java.awt.Label.CENTER);
        Description7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        SelectButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton7.setLabel("Select");
        SelectButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton7ActionPerformed(evt);
            }
        });

        SelectButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SelectButton2.setLabel("Select");
        SelectButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuizzesPanelLayout = new javax.swing.GroupLayout(QuizzesPanel);
        QuizzesPanel.setLayout(QuizzesPanelLayout);
        QuizzesPanelLayout.setHorizontalGroup(
            QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizzesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizzesPanelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizzesPanelLayout.createSequentialGroup()
                        .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Title3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(Title4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(Title5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(Title6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(Title7, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(Description3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SelectButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(SelectButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QuizzesPanelLayout.setVerticalGroup(
            QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizzesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SelectButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Description3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuizzesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        ShowQuizzes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowQuizzes.setLabel("Click here to show the quizzes");
        ShowQuizzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowQuizzesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentMenuPanelLayout = new javax.swing.GroupLayout(StudentMenuPanel);
        StudentMenuPanel.setLayout(StudentMenuPanelLayout);
        StudentMenuPanelLayout.setHorizontalGroup(
            StudentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StudentMenuPanelLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(ShowQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentMenuPanelLayout.createSequentialGroup()
                .addComponent(QuizzesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        StudentMenuPanelLayout.setVerticalGroup(
            StudentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ShowQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuizzesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(StudentMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(StudentMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Quiz DeserializeData()
    {        
      Quiz e = null;    
        try {
         FileInputStream fileIn = new FileInputStream("SavedSerializedData.ser");
         ObjectInputStream in = new ObjectInputStream(fileIn);
         e = (Quiz)in.readObject();
         in.close();
         fileIn.close();
      }catch(IOException i) {
         i.printStackTrace();
         return null;
      }catch(ClassNotFoundException c) {
         c.printStackTrace();
         return null;
      }
      return e;  
}
            
    private void SelectButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton2ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,2);
        Quizer.setVisible(true);

    }//GEN-LAST:event_SelectButton2ActionPerformed

    private void SelectButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton7ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,7);
        Quizer.setVisible(true);
    }//GEN-LAST:event_SelectButton7ActionPerformed

    private void SelectButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton6ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,6);
        Quizer.setVisible(true);
    }//GEN-LAST:event_SelectButton6ActionPerformed

    private void SelectButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton5ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,5);
        Quizer.setVisible(true);
    }//GEN-LAST:event_SelectButton5ActionPerformed

    private void SelectButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton4ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,4);
        Quizer.setVisible(true);
    }//GEN-LAST:event_SelectButton4ActionPerformed

    private void SelectButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton3ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,3);
        Quizer.setVisible(true);
    }//GEN-LAST:event_SelectButton3ActionPerformed

    private void SelectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButton1ActionPerformed
        this.dispose();
        StudentAttemptsQuiz Quizer = new StudentAttemptsQuiz(userName,1);
        Quizer.setVisible(true);
    }//GEN-LAST:event_SelectButton1ActionPerformed

    private void ShowQuizzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowQuizzesActionPerformed
        QuizzesPanel.setVisible(true);
        int QuizNumber = 1;
        boolean loopRunCheck = false;
        String record = null;
	FileReader in = null;
	try {
	in = new FileReader("Quizzes.txt");
	BufferedReader br = new BufferedReader(in);

	while ((record = br.readLine()) !=null) 
	{            
            loopRunCheck = true;            
            String[] parts = record.split("--------");             
            String Title = parts[0]; 
            String Description = parts[1];
            int QuestionNumber = Integer.parseInt(parts[4]);
             
            if(QuizNumber>0 && QuestionNumber == 1)
            {
                if(QuizNumber == 1)
                {
                Title1.setText(Title);                
                Description1.setText(Description);
                SelectButton1.setVisible(true);    
                }
                else if(QuizNumber == 2)
                {
                Title2.setText(Title);                
                Description2.setText(Description);
                SelectButton2.setVisible(true);    
                }
                else if(QuizNumber == 3)
                {
                Title3.setText(Title);                
                Description3.setText(Description);
                SelectButton3.setVisible(true);    
                }
                else if(QuizNumber == 4)
                {
                Title4.setText(Title);                
                Description4.setText(Description);
                SelectButton4.setVisible(true);    
                }
                else if(QuizNumber == 5)
                {
                Title5.setText(Title);                
                Description5.setText(Description);
                SelectButton5.setVisible(true);    
                }
                else if(QuizNumber == 6)
                {
                Title6.setText(Title);                
                Description6.setText(Description);
                SelectButton6.setVisible(true);    
                }
                else if(QuizNumber == 7)
                {
                Title7.setText(Title);                
                Description7.setText(Description);
                SelectButton7.setVisible(true);    
                }                
                QuizNumber++;                 
            }                        
        }
        br.close();  
        if(loopRunCheck==false)
            {
                String[] options = {"Logout","Exit program"};
                int n = JOptionPane.showOptionDialog(null,"There are no quizzes available at the moment.\nPlease come back later.\n","No quizzes available",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
                    if(options[n].contains("Logout"))
                    {
                    this.dispose();                            
                    Login newUser = new Login();
                    newUser.setVisible(true);
                    }
                    else if(options[n].contains("Exit program"))
                    {
                    System.exit(0);        
                    }       
            }
        } 		        
        catch (IOException e) {
	e.getCause();
	}  
       
    }//GEN-LAST:event_ShowQuizzesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMenu(userName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Description1;
    private java.awt.Label Description2;
    private java.awt.Label Description3;
    private java.awt.Label Description4;
    private java.awt.Label Description5;
    private java.awt.Label Description6;
    private java.awt.Label Description7;
    private javax.swing.JPanel QuizzesPanel;
    private java.awt.Button SelectButton1;
    private java.awt.Button SelectButton2;
    private java.awt.Button SelectButton3;
    private java.awt.Button SelectButton4;
    private java.awt.Button SelectButton5;
    private java.awt.Button SelectButton6;
    private java.awt.Button SelectButton7;
    private java.awt.Button ShowQuizzes;
    private javax.swing.JPanel StudentMenuPanel;
    private java.awt.Label Title1;
    private java.awt.Label Title2;
    private java.awt.Label Title3;
    private java.awt.Label Title4;
    private java.awt.Label Title5;
    private java.awt.Label Title6;
    private java.awt.Label Title7;
    private java.awt.Label WelcomeMessage;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables


}
